IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AppPlatform]') AND type in (N'U'))
    DROP TABLE [dbo].[AppPlatform]
GO

CREATE TABLE [dbo].[AppPlatform](
    [RowId] INT NOT NULL IDENTITY(1,1),
    [Key] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [Name] NVARCHAR(256) NOT NULL DEFAULT '',
	[PlatformType] INT NOT NULL DEFAULT 0,
	[BundleId] [NVARCHAR](256) NULL,
	[Url] [NVARCHAR](256) NULL,
	[MinOSVersion] [NVARCHAR](64) NULL,
    [Description] [NVARCHAR](MAX) NULL,
    [CreatedStamp] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [LastUpdatedStamp] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [CreatedBy] UNIQUEIDENTIFIER NULL,
    [LastUpdatedBy] UNIQUEIDENTIFIER NULL,
    [State] [int] NOT NULL DEFAULT 0,
CONSTRAINT [PK_AppPlatform_Key] PRIMARY KEY NONCLUSTERED 
(
    [Key] ASC
),
CONSTRAINT [CIX_AppPlatform] UNIQUE CLUSTERED 
(
    [RowId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

GO

