CREATE TABLE [dbo].[SystemConfiguration](
    [RowId] INT NOT NULL IDENTITY(1,1),
    [Key] [NVARCHAR](64) NOT NULL,
    [Type] [NVARCHAR](256) NOT NULL,
    [Value] [NVARCHAR](MAX) NOT NULL,
    [MinComponentVersionRequired] [NVARCHAR](32) NULL,
    [MaxComponentVersionLimited] [NVARCHAR](32) NULL,
    [CreatedStamp] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [LastUpdatedStamp] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [State] [int] NOT NULL DEFAULT 0,
CONSTRAINT [PK_SystemConfiguration_Key] PRIMARY KEY NONCLUSTERED 
(
    [Key] ASC
),
CONSTRAINT [CIX_SystemConfiguration] UNIQUE CLUSTERED 
(
    [RowId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

GO
